apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  labels:
    app: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: laleth2614/laleth2:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://rockey1533:123456789+@cluster0.8v8hbea.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
