apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  selector:
    app: todolist
    ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
